# DEXCOM API KEYS NEED TO BE PROVIDED FOR UNCOMPILED BUILDS To Be ABLE TO USE THE DEXCOM FUNCTIONALITY!
# USING THE FUNCTIONALITY WITHOUT API KEYS WILL RETURN ERRORS!

CLIENT_ID = ''
CLIENT_SECRET = ''
REDIRECT_URI = ''

